import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useState } from "react";

import Head from "next/head";
import Model from "../components/Model/Model";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [text, setText] = useState("");

  useEffect(() => {
    const handleInput = () => {
      if (text === "meetme") {
        router.push({
          pathname: "/bio",
        });
      }
    };
    handleInput();
  }, [router, text]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <div className={styles.two_col}>
          <div className={styles.left_col}>
            <AnimatePresence>
              <motion.div
                className={styles.left_col_top}
                initial="hidden"
                animate="visible"
                variants={{
                  hidden: {
                    scale: 0.8,
                    opacity: 0,
                  },
                  visible: {
                    scale: 1,
                    opacity: 1,
                    transition: {
                      delay: 0.4,
                      duration: 0.4,
                    },
                  },
                }}
              >
                <p>Greetings. This is my site</p>
                <h1>I'm Liam</h1>
                <h3>Senior software engineer</h3>
              </motion.div>
            </AnimatePresence>
            <div className={styles.left_col_bottom}>
              <div style={{ display: "flex", gap: "10px" }}>
                <motion.p
                  initial="hidden"
                  animate="visible"
                  variants={{
                    hidden: {
                      x: "-100px",
                      opacity: 0,
                    },
                    visible: {
                      x: 0,
                      opacity: 1,
                      transition: {
                        delay: 0.4,
                        duration: 0.4,
                      },
                    },
                  }}
                  // eslint-disable-next-line react/jsx-no-comment-textnodes
                >
                  $
                </motion.p>
                <motion.p
                  initial="hidden"
                  animate="visible"
                  variants={{
                    hidden: {
                      x: "100px",
                      opacity: 0,
                    },
                    visible: {
                      x: 0,
                      opacity: 1,
                      transition: {
                        delay: 0.4,
                        duration: 0.4,
                      },
                    },
                  }}
                >
                  type the prompt below for a trivial little gimmick
                </motion.p>
              </div>
              <motion.div
                className={styles.input}
                whileHover={{
                  scale: [1, 1.4, 1.2],
                  transition: {
                    duration: 0.2,
                  },
                }}
              >
                <p>&#x276F;</p>
                <input
                  type="text"
                  placeholder="meetme"
                  onChange={(e) => setText(e.target.value)}
                />
              </motion.div>
            </div>
          </div>
          <div className={styles.right_col}>
            <Model />
          </div>
        </div>
      </div>
    </div>
  );
}
